version: '2.2'
services:

  iqlogger:
    build: .
    ports:
      - 12201:12201
      - 12202:12202
      - 8888:8888

  sender:
    build: ./sender/
    depends_on:
      - iqlogger
    environment:
      - TEST_MESSAGE_COUNT=${TEST_MESSAGE_COUNT}
      - TEST_DURATION=${TEST_DURATION}

  receiver:
    build: ./receiver/
    depends_on:
      - iqlogger
      - sender
    environment:
      - TEST_MESSAGE_COUNT=${TEST_MESSAGE_COUNT}
      - TEST_DURATION=${TEST_DURATION}